apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-data-policy
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    interfaces:
    - name: br-data
      description: |-
        A dedicated OVS bridge with bond0 as a port
      type: ovs-bridge
      state: up
      ipv4:
        enabled: false 
      ipv6:
        enabled: false      
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: 
            enabled: false
        port:
        - name: {{ .Values.bond.name }}