apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/nodeSelector/kubernetes.io~1hostname
      value: worker02
    - op: replace
      path: /spec/desiredState/interfaces/0/name
      value: bond1
    - op: replace 
      path: /spec/desiredState/interfaces/0/ipv4/address/0/ip
      value: '10.0.2.10'
    - op: replace
      path: /spec/desiredState/interfaces/0/link-aggregation/port/0
      value: 'enp0s1'
    - op: replace
      path: /spec/desiredState/interfaces/0/link-aggregation/port/1
      value: 'enp0s2'
    - op: add
      path: /spec/desiredState/interfaces/0/link-aggregation/port/-
      value: 'enp0s3'
    - op: replace
      path: /spec/desiredState/dns-resolver/config/server/0
      value: '10.0.2.53'
    - op: replace
      path: /spec/desiredState/routes/config/0/next-hop-address
      value: '10.0.2.1'
    - op: replace
      path: /spec/desiredState/routes/config/0/next-hop-interface
      value: bond1
  target:
    kind: NodeNetworkConfigurationPolicy
    name: bond-worker-policy
- patch: |-
    - op: replace
      path: /spec/desiredState/interfaces/0/bridge/port/0/name
      value: bond1
  target:
    kind: NodeNetworkConfigurationPolicy
    name: br-data-policy
- patch: |-
    - op: replace
      path: /spec/desiredState/ovn/bridge-mappings/0/localnet
      value: vlan20-net
  target:
    kind: NodeNetworkConfigurationPolicy
    name: br-data-vlan-policy