apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-data-bond-policy
spec:
  nodeSelector:
    node-role.kubernetes.io/worker: '' 
  desiredState:
    interfaces:
    - name: br-data
      description: |-
        A dedicated OVS bridge with bond1 as a port
        allowing VLAN 20
      type: ovs-bridge
      state: up
      ipv4:
        enabled: false 
      ipv6:
        enabled: false      
      bridge:
        allow-extra-patch-ports: true
        options:
          stp: 
            enabled: false
        port:
        - name: bond0
    ovn:
      bridge-mappings:
      - bridge: br-data
        localnet: vlan20-net
        state: present
